### ISSUE TITLE
Issues when doing zalgo

### ISSUE THREAD

**Issue by filthycoding** [cozyplanes/devBanner#13]
Using the following text in the text field...

w̛͎̩͚̙̒̉a̴̱ͫ̈́́́͞i̡̗ͪ̾̅̾͢͞͞t̜͇ͮ͊̒̈́ ̸̷͞į̛͚̄ͭ͘͡ ̀ͦt̄̓͠hͣ̾͡i̢͓̕͡҉n͔͙k̡̺ͥ ̶̻̆̒̊̉̕͝i̶̯̳̱̰̅̌́͠͡m̪͆̕̕͟ ̧͜͝ḓ̵͉̠̱̀̈͑͠ò͚͌͆͜ǐͮͣ̇n̛̫ͭ͑̾ͬg̘̼̈́̀̚҉̨ ̵̷̭̤̱̀̆̕i͖ͤ̚͡͡ț̯ͫ̕͢ ̗҉w̶̴̦͂̋͢r̸̶͖̣̫̖̔̀͞ố̉̆́͝͞҉n̹͚̭͒ͫ̏͠g̸̵̢̜͞ ̴̡̆̏ͪ̑͢s̢̭̈́̅̀̀͞h̽͋̍̏i̸͉̯͇͕̇́t̟̗̺͆

...doesn't give me a banner at all.

**Comment by Kimmax** [comment]
Somewhat related to #15 
The webserver probably does not handle UTF-8 well.

A problem on our side is indeed the handling of uncommon UTF-8 symbols, since the used font does not provide them all.
Im not sure if we need support for them.. I personally don't think so..

**Comment by cozyplanes** [comment]
A normal human being does not use zalgo
