### ISSUE TITLE
Bashlord's frontend is flawed

### ISSUE THREAD

**Issue by Kimmax** [cozyplanes/devBanner#15]
The frontend provided by Bashlord is not well tested and has some problems. One of the most risky one is, that it stores provided input's unencoded and is therefor vulnerable to XSS. 
**I therefore propose that we remove the frontend from the repo until all flaws are fixed and the site was well tested.**

**Comment by MatiasConTilde** [comment]
<img src="http://www.gifbin.com/bin/1232905464_Rickrolled.gif" width="640" height="480"><audio autoplay loop><source src="https://firebasestorage.googleapis.com/v0/b/matias-con-tilde.appspot.com/o/rickroll.mp3?alt=media"></audio>
