### ISSUE TITLE
Why a server for this? 

### ISSUE THREAD

**Issue by alberto98fx** [cozyplanes/devBanner#17]
https://gist.github.com/alberto98fx/f90d29cfaf8013aa0de44e7dbe6e6fef 

Live demo here

https://rawgit.com/alberto98fx/f90d29cfaf8013aa0de44e7dbe6e6fef/raw/556829e80bf05ca2ec9dc9df048ac0a2dee2930a/devrant.html

**Comment by RekkyRek** [comment]
How about the correct font? It would require everyone to have Comfortaa installed wouldn't it?

**Comment by alberto98fx** [comment]
```
<style type="text/css">
@font-face {
    font-family: "My Custom Font";
    src: url(http://www.example.org/mycustomfont.ttf) format("truetype");
}
p.customfont { 
    font-family: "My Custom Font", Verdana, Tahoma;
}
</style>
<p class="customfont">Hello world!</p>
```

**Comment by alberto98fx** [comment]
Something like this?

**Comment by RekkyRek** [comment]
But this does not generate an image tho

**Comment by alberto98fx** [comment]
`toDataURL("image/png");`

**Comment by alberto98fx** [comment]
Since you are using .tff here's the Browser support list

**Comment by alberto98fx** [comment]
https://www.w3schools.com/css/css3_fonts.asp  

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

**Comment by Kimmax** [comment]
Sure, we can do it in the browser, however my goal is to make it usable by calling an api.
Suppose you want a banner with your current stats in a signature _somewhere_, you point the picture url to the endpoint, set your settings and done
Generating this locally would mean that you would have to get js to run by pointing to a picture, which would not work
Also running a server we can do many more things like caching the results on the fly and add options for devrant supporters only

**Comment by alberto98fx** [comment]
I think that the devRant API is enough for this kind of things... 

https://www.devrant.io/api/users/202062?app=3&plat=2&content=all&skip=0 

You could check if a user is supporter or not with `"user_dpp":1` 

As you can see, you have a lot of stuff there as well as stats of the user etc.. 

I woud consider the client-side (cheap) solution... 

No need to cache if it runs on the client, right? 😄

**Comment by Kimmax** [comment]
We're already using the API.
You didn't get my main point.
You can't point a picture to some side that requires you to run js to generate the image.
With the server solution we can generate the banner and return a image/png just fine
Caching is to avoid the devRant avatar server's since they are rather slowish and to take load of them

**Comment by Kimmax** [comment]
@CozyPlanes what more information do you need..

**Comment by cozyplanes** [comment]
I thought you were considering. You can close if you want
