### ISSUE TITLE
Sub text discards plus symbol

### ISSUE THREAD

**Issue by ThomasRedstone** [cozyplanes/devBanner#18]
May affect other characters.

**Comment by Kimmax** [comment]
The plus is symbol is not discarded but has a special meaning in URLs (whitespace).
That means your plus is converted to a space by your browser. If you URL encode the symbol (%2b) the symbol appears correctly

**Comment by ThomasRedstone** [comment]
Maybe you should fix the demo to URL encode correctly then?

**Comment by Kimmax** [comment]
If you're talking about the readme, is no plus in that url?
If you're talking about the URL encode itself, that's nothing we can control..
