### ISSUE TITLE
Report Text Render Errors Here

### ISSUE THREAD

**Issue by cozyplanes** [cozyplanes/devBanner#5]
If the characters look weird in the generated banner, please post the following.
- Generated banner
- URL (or program version)
- Generated Date (ex Nov 27)
- Characters that renders incorrectly

Thank you!

**Comment by gitpushdev** [comment]
- Generated Banner: ![banner](https://user-images.githubusercontent.com/34022105/33258088-1755d658-d361-11e7-8b7a-033afc03b4d2.png)
- Url: https://devrant.nuernberger.kim/api/banner?username=Kimmax&subtext=new%20Rant(%22I%20fucked%20up!%22);
- Time: 10 AM (+2 GMT)
- Characters that render incorrectly: semicolon ;

**Comment by cozyplanes** [comment]
- Generated banner
![immagine](https://user-images.githubusercontent.com/4522930/33245846-a358842e-d30d-11e7-838f-0e30743d07cf.png)
![immagine](https://user-images.githubusercontent.com/4522930/33245847-a574eb30-d30d-11e7-970a-6f0896ef063f.png)

- URL
https://devrant.nuernberger.kim/api/banner?username=JS96&subtext=9
https://devrant.nuernberger.kim/api/banner?username=Parham3679srsr&subtext=9

- Time
Unknown

- Characters that renders incorrecctly
9

**Comment by Kimmax** [comment]
I suspect the font got damaged while deploying.
Related: #3

**Comment by cozyplanes** [comment]
Seems that it is fixed now, will close after final check

**Comment by Kimmax** [comment]
All broken cases validated by @JakubSteplowski 
Thanks!

**Comment by cozyplanes** [comment]
@Kimmax You don't close issues by your own, ok? lol
